version: '3.8'

services:
  nutriscan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutriscan-pwa
    restart: unless-stopped
    ports:
      - "2025:3000"
    environment:
      - NODE_ENV=production
