version: '3.8'

services:
  nutriscan:
    image: atemnbobs/nutriscan-amd64:v0.0.1
    container_name: nutriscan-pwa
    restart: unless-stopped
    ports:
      - "2025:3000"
    environment:
      - NODE_ENV=production
