name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: nutriscan.atemkeng.de
        username: atem
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd /home/atem/docker/nutriscan
          git pull origin main
          docker build -t nutriscan-pwa:latest .
          docker-compose down -v --rmi all
          docker-compose up -d
          docker image prune -f
